# Generated by Django 5.1 on 2025-01-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_number',
            field=models.CharField(max_length=100),
        ),
    ]
