# Generated by Django 5.1 on 2024-08-12 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_company_id_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 6, 6, 59, 792656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 6, 6, 59, 792656, tzinfo=datetime.timezone.utc)),
        ),
    ]
