# Generated by Django 5.1 on 2024-08-10 07:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(choices=[('email', 'Email'), ('call', 'Call'), ('other', 'Other')], max_length=100)),
                ('status', models.TextField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress'), ('new', 'New'), ('cancelled', 'Cancelled')], max_length=50)),
                ('due_date', models.DateField(default=datetime.date(2024, 8, 10))),
                ('comments', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in-progress', 'In-Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('needs-review', 'Needs Review'), ('cancelled', 'Cancelled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.contact')),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket_subtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.subtype')),
                ('ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.type')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='subtype',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.type'),
        ),
    ]
