# Generated by Django 5.1 on 2024-11-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('completed', 'Completed'), ('in-progress', 'In Progress'), ('scheduled', 'Scheduled'), ('new', 'New'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
