# Generated by Django 5.1 on 2024-08-12 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_note_id_alter_subtype_id_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 6, 6, 59, 792656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='subtype',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 6, 6, 59, 792656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 6, 6, 59, 792656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 6, 6, 59, 792656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='type',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 12, 6, 6, 59, 792656, tzinfo=datetime.timezone.utc)),
        ),
    ]
