# Generated by Django 5.1 on 2024-08-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_note_updated_at_alter_subtype_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='New Task', max_length=255),
            preserve_default=False,
        ),
    ]
