# Generated by Django 5.1 on 2024-08-16 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_company_contact_name_remove_contact_company_and_more'),
        ('service', '0005_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='contact_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.contact'),
        ),
    ]
