# Generated by Django 5.1 on 2024-10-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_note_updated_at_alter_subtype_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
