# Generated by Django 5.1 on 2024-09-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='app_label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
