# Generated by Django 5.1 on 2024-08-30 07:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('num_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('Webinar', 'Webinar'), ('Conference', 'Conference'), ('Public Relations', 'Public Relations'), ('Advertisement', 'Advertisement'), ('Banners', 'Banners')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_response', models.IntegerField()),
                ('leads', models.ManyToManyField(related_name='campaigns', to='customer.contact')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owner', to=settings.AUTH_USER_MODEL)),
                ('responses', models.ManyToManyField(blank=True, related_name='responses', to='customer.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('num_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity_name', models.CharField(max_length=255)),
                ('company_name', models.TextField(max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stage', models.CharField(choices=[('Open Discussion', 'Open Discussion'), ('Not Started', 'Not Started'), ('Closed - Won', 'Closed - Won'), ('Closed - Lost', 'Closed - Lost')], max_length=20)),
                ('campaign_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.campaign')),
                ('contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.contact')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifier', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
