# Generated by Django 5.1 on 2024-08-14 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_company_updated_at_alter_contact_updated_at'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='company_name',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='customer.company'),
        ),
    ]
