# Generated by Django 5.1 on 2024-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_opportunity_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='company_name',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
