# Generated by Django 5.1 on 2024-08-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_campaign_created_at_campaign_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='expected_response',
            field=models.IntegerField(),
        ),
    ]
